tools:
    build: .
    ports:
        - "8080:8080"
        - "8888:8888"
    # blueprint document folder path
    volumes:
        - /vagrant/sample:/blueprint
    # index page filename
    environment:
        BLUEPRINT_TOOLS_DOC_INDEX: index.md
